# Welcome to NumPy:

In [1]:
import numpy as np

In [2]:
#1D array and it type declaration.
myarr = np.array([3,6,32,7], np.int64) 

In [3]:
myarr

array([ 3,  6, 32,  7], dtype=int64)

In [4]:
myarr[3]

7

In [5]:
# 2D array and its type declaration.
myarr = np.array([[3,6,32,7]], np.int32) 

In [6]:
myarr[0,1]

6

In [7]:
#gives the shape of array.
myarr.shape 

(1, 4)

In [8]:
#gives the datatype it made of.
myarr.dtype 

dtype('int32')

In [9]:
myarr[0,1]

6

In [10]:
myarr[0,1] = 45

In [13]:
myarr

array([[ 3, 45, 32,  7]])

# Array creation: Conversion from the Python structures

In [14]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [15]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
listarray.dtype

dtype('int32')

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [20]:
# Python objects
np.array({34,23,23})
# prefer not to work on objects.
# Work on int and float datatype.

array({34, 23}, dtype=object)

In [21]:
# .zeros give the zeros in provided shape.
zeros = np.zeros((2,5))

In [22]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
zeros.size

10

In [27]:
# work as range and give numpy array of perticular size.
rng = np.arange(15)

In [28]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [29]:
# linspace provide equal space in provided range.
# (start, stop, num of time required space)
lspace = np.linspace(1,5,10)

In [30]:
lspace

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [31]:
lspace = np.linspace(1,5,5)

In [32]:
lspace

array([1., 2., 3., 4., 5.])

In [35]:
# It create a empty array or given size and we can assign values to it.
emp = np.empty((4,6))

In [36]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511290e-306, 6.23058368e-307, 8.45593934e-307],
       [7.56593017e-307, 1.11261027e-306, 1.11261502e-306,
        1.42410839e-306, 7.56597770e-307, 6.23059726e-307],
       [1.42419530e-306, 7.56602523e-307, 1.29061821e-306,
        9.34600963e-307, 7.56602523e-307, 8.34451079e-308],
       [1.39071445e-307, 1.33511562e-306, 8.90103560e-307,
        1.42410974e-306, 1.00132228e-307, 1.33511969e-306]])

In [39]:
# It take already defined array size and used it create copy array
# We do this for effeciancy.
emp_like = np.empty_like(lspace)

In [40]:
emp_like

array([1., 2., 3., 4., 5.])

In [46]:
# It give identity matrix of provided size. Used in algebra.
ide = np.identity(45)

In [47]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [48]:
ide.shape

(45, 45)

In [49]:
arr = np.arange(99)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [52]:
# It reshape into given dimension. and dimension have to be multiple of range.
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [55]:
# assign the value to change permanently.
arr = arr.reshape(3,33)

In [56]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [57]:
# It reversed the reshape into 1D array.
arr = arr.ravel()

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [59]:
arr.shape

(99,)

In [60]:
# 1D: [axis0]
# 2D: [axis0,axis1] (rows ↓ , column →)

In [61]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [62]:
ar = np.array(x)

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
# it add 1+4+7=12 like vice; 
ar.sum(axis=0)

array([12,  8,  9])

In [65]:
# it add 1+2+3=6 like vice; 
ar.sum(axis=1)

array([ 6, 15,  8])

In [67]:
# .T transposed the row into column and column into row.
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [70]:
# we can iterate the data by using for loop.
ar.flat

In [71]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [72]:
# It show the number of dimension.
# we refer these as an attibutes
ar.ndim

2

In [74]:
# show size of array.
ar.size

9

In [75]:
# show total bytes consume.
ar.nbytes

36

In [83]:
one = np.array([1,3,4,643,2])

In [84]:
# show maximum value index location.
# we refer these as function.
one.argmax()

3

In [85]:
# show minimum value index.
one.argmin()

0

In [86]:
# show sorted array index location.
# sort 1D array.
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [87]:
ar 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [88]:
# sort 2D array
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [89]:
# show max number position index in 2D array.
ar.argmax()

6

In [90]:
ar.argmin()

8

In [91]:
# show sequence of maximum number in respective x-axis.
ar.argmax(axis = 0)

array([2, 1, 1], dtype=int64)

In [92]:
ar.argmax(axis = 1)

array([2, 2, 0], dtype=int64)

In [93]:
# sort according to given axis.
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [94]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [95]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [96]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [97]:
ar.reshape((9,))

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [98]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [99]:
ar2 = np.array([[1, 5, 3],
       [2, 3, 5],
       [7, 9, 0]])

In [100]:
# Numpy give function to add matrix row and column.
ar + ar2

array([[ 2,  7,  6],
       [ 6,  8, 11],
       [14, 10,  0]])

In [102]:
# python does not provide this feature.
[324, 34] +[34, 34]

[324, 34, 34, 34]

In [103]:
ar*ar2

array([[ 1, 10,  9],
       [ 8, 15, 30],
       [49,  9,  0]])

In [105]:
# show square root of given array.
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [108]:
# sum of all number.
ar.sum()

29

In [110]:
# show maximum number
ar.max()

7

In [111]:
ar.min()

0

In [112]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [114]:
# show the position [x,y] of operation.
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [115]:
type(np.where(ar>5))

tuple

In [116]:
# show total non zero values in array.
np.count_nonzero(ar)

8

In [118]:
# show positon of non zero element in [x,y]
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [120]:
ar[1,2]= 0

In [121]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [122]:
import sys

In [123]:
py_ar = [0,4,33,2]

In [124]:
np_ar = np.array(py_ar)

In [125]:
# sys.getsizeof(1) show the Python list size of 1 item.
sys.getsizeof(1) * len(py_ar)

112

In [127]:
# .itemsize show the size of 1 item in array.
np_ar.itemsize * np_ar.size

16

In [128]:
# This show the difference in size of item.
# Single item size show whole file size.
# That's why we prefer NumPy for mathmatical calculation.
# NumPy reduce size and make file work faster.

In [129]:
# Google "Numpy array methods and attributes"
# Practice all.

In [131]:
# Example:
# It convert array into pyhton list datatype.
np_ar.tolist()

[0, 4, 33, 2]